version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
    - "3306:3308"
    environment:
      MYSQL_ROOT_PASSWORD: "nimda"
      MYSQL_DATABASE: "ecom"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "nimda"
    expose:
      - "3306"
#    networks:
#      - docnet
  web:
    build: .
    restart: always
    ports:
    - "8000:8000"
    depends_on:
      - "db"
    links:
      - "db:db"
#    networks:
#      - docnet
    command: "python manage.py runserver 0.0.0.0:8000"
#networks:
#  docnet:
#    external: true